export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SET_ALL_FILTER_PRODUCTS = 'SET_ALL_PRODUCTS';
export const SET_PRODUCTS_PER_PAGE = 'SET_PRODUCTS_PER_PAGE';
export const SET_SORT_BY_PRICE = 'SET_SORT_BY_PRICE';
export const SET_SORT_BY_RATE = 'SET_SORT_BY_RATE';
export const SET_SORT_BY_DATE = 'SET_SORT_BY_DATE';
export const SET_SORT_BY_POPULARITY = 'SET_SORT_BY_POPULARITY';
