const SET_CART_ITEMS = 'SET_CART_ITEMS';
const SET_ITEM_TO_CART = 'SET_ITEM_TO_CART';
const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export { SET_ITEM_TO_CART, REMOVE_ITEM_FROM_CART, SET_CART_ITEMS };
