const SET_CART = 'SET_CART';
const GET_CART = 'GET_CART';
const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
const SET_CART_ITEM_QUANTITY = 'SET_CART_ITEM_QUANTITY';

export {
  SET_CART,
  GET_CART,
  ADD_ITEM_TO_CART,
  REMOVE_ITEM_FROM_CART,
  SET_CART_ITEM_QUANTITY
};
