const SET_WISHLIST = 'SET_WISHLIST';
const GET_WISHLIST = 'GET_WISHLIST';
const ADD_ITEM_TO_WISHLIST = 'ADD_ITEM_TO_WISHLIST';
const REMOVE_ITEM_FROM_WISHLIST = 'REMOVE_ITEM_FROM_WISHLIST';

export {
  SET_WISHLIST,
  GET_WISHLIST,
  ADD_ITEM_TO_WISHLIST,
  REMOVE_ITEM_FROM_WISHLIST
};
