const SET_WISHLIST_ITEMS = 'SET_WISHLIST_ITEMS';
const SET_ITEM_TO_WISHLIST = 'SET_ITEM_TO_WISHLIST';
const REMOVE_ITEM_FROM_WISHLIST = 'REMOVE_ITEM_FROM_WISHLIST';

export { SET_WISHLIST_ITEMS, SET_ITEM_TO_WISHLIST, REMOVE_ITEM_FROM_WISHLIST };
