const routes = {
  pathToNews: '/news',
  pathToSingleNews: '/news/:id',
  pathToConstructor: '/constructor',
  pathToWishlist: '/wishlish',
  pathToContacts: '/contacts',
  pathToMaterials: '/materials',
  pathToChosenPage: '/pages/:page',
  pathToConfirmationToken: '/confirmation/:token',
  pathToRecoveryToken: '/recovery/:token',
  pathToOrderHistory: '/order-history',
  pathToChosenProduct: '/product/:id',
  pathToLogin: '/login',
  pathToRecovery: '/recovery',
  pathToRegister: '/register',
  pathToAllProducts: '/catalog/products',
  pathToProducts: '/product',
  pathToErrorPage: '/error-page',
  pathToNotFoundPage: '/not-found',
  pathToBackpacks: '/backpacks',
  pathToCategory: '/catalog/:category',
  pathToCheckout: '/checkout',
  pathToCart: '/cart',
  pathToMain: '/',
  pathToThanks: '/thanks',
  pathToProfile: '/profile',
  pathToTerms: '/pages/terms',
  pathToUserAgreement: '/pages/user-agreement',
  pathToAnswersQuestionsPage: '/answers-questions'
};

export default routes;
