export const GET_MODEL_FOR_CONSTRUCTOR = 'GET_MODEL_FOR_CONSTRUCTOR';
export const SET_MODEL_FOR_CONSTRUCTOR = 'SET_MODEL_FOR_CONSTRUCTOR';
export const GET_CONSTRUCTOR_MODEL_BY_ID = 'GET_CONSTRUCTOR_MODEL_BY_ID';
export const SET_CONSTRUCTOR_MODEL_BY_ID = 'SET_CONSTRUCTOR_MODEL_BY_ID';
export const SET_MODEL_LOADING = 'SET_MODEL_LOADING';
