const GET_BURGER_MENU_LINKS = 'GET_BURGER_MENU';
const SET_BURGER_MENU_LINKS = 'SET_BURGER_MENU';
const SET_BURGER_MENU_LOADING_LINKS = 'SET_BURGER_MENU_LOADING';

export {
  GET_BURGER_MENU_LINKS,
  SET_BURGER_MENU_LINKS,
  SET_BURGER_MENU_LOADING_LINKS
};
