const GET_BURGER_MENU = 'GET_BURGER_MENU';
const SET_BURGER_MENU = 'SET_BURGER_MENU';
const SET_BURGER_MENU_LOADING = 'SET_BURGER_MENU_LOADING';

export { GET_BURGER_MENU, SET_BURGER_MENU, SET_BURGER_MENU_LOADING };
