const GET_NOVAPOSHTA_CITIES = 'GET_NOVAPOSHTA_CITIES';
const SET_NOVAPOSHTA_CITIES = 'SET_NOVAPOSHTA_CITIES';
const GET_NOVAPOSHTA_WAREHOUSES = 'GET_NOVAPOSHTA_WAREHOUSES';
const SET_NOVAPOSHTA_WAREHOUSES = 'SET_NOVAPOSHTA_WAREHOUSES';
const SET_LOADING = 'SET_LOADING';
const GET_NOVAPOSHTA_STREETS = 'GET_NOVAPOSHTA_STREETS';
const SET_NOVAPOSHTA_STREETS = 'SET_NOVAPOSHTA_STREETS';

export {
  GET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_WAREHOUSES,
  GET_NOVAPOSHTA_WAREHOUSES,
  SET_LOADING,
  GET_NOVAPOSHTA_STREETS,
  SET_NOVAPOSHTA_STREETS
};
