const GET_NOVAPOSHTA_CITIES = 'GET_NOVAPOSHTA_CITIES';
const GET_NOVAPOSHTA_WAREHOUSES = 'GET_NOVAPOSHTA_WAREHOUSES';
const GET_NOVAPOSHTA_PRICES = 'GET_NOVAPOSHTA_PRICES';
const SET_NOVAPOSHTA_CITIES = 'SET_NOVAPOSHTA_CITIES';
const SET_NOVAPOSHTA_WAREHOUSES = 'SET_NOVAPOSHTA_WAREHOUSES';
const SET_NOVAPOSHTA_PRICES = 'SET_NOVAPOSHTA_PRICES';
const SET_DELIVERY_LOADING = 'SET_DELIVERY_LOADING';
const SET_FONDY_DATA = 'SET_FONDY_DATA';

export {
  GET_NOVAPOSHTA_CITIES,
  GET_NOVAPOSHTA_WAREHOUSES,
  GET_NOVAPOSHTA_PRICES,
  SET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_WAREHOUSES,
  SET_NOVAPOSHTA_PRICES,
  SET_DELIVERY_LOADING,
  SET_FONDY_DATA
};
