const GET_NOVAPOSHTA_CITIES = 'GET_NOVAPOSHTA_CITIES';
const GET_NOVAPOSHTA_WAREHOUSES = 'GET_NOVAPOSHTA_WAREHOUSES';
const GET_NOVAPOSHTA_PRICES = 'GET_NOVAPOSHTA_PRICES';
const SET_NOVAPOSHTA_CITIES = 'SET_NOVAPOSHTA_CITIES';
const SET_NOVAPOSHTA_WAREHOUSES = 'SET_NOVAPOSHTA_WAREHOUSES';
const SET_NOVAPOSHTA_PRICES = 'SET_NOVAPOSHTA_PRICES';
const SET_DELIVERY_LOADING = 'SET_DELIVERY_LOADING';
const SET_FONDY_DATA = 'SET_FONDY_DATA';
const GET_UKRPOST_CITIES = 'GET_UKRPOST_CITIES';
const GET_UKRPOST_DISTRICTS = 'GET_UKRPOST_DISTRICTS';
const GET_UKRPOST_POSTOFFICES = 'GET_UKRPOST_POSTOFFICES';
const GET_UKRPOST_REGIONS = 'GET_UKRPOST_REGIONS';
const SET_UKRPOST_CITIES = 'SET_UKRPOST_CITIES';
const SET_UKRPOST_DISTRICTS = 'SET_UKRPOST_DISTRICTS';
const SET_UKRPOST_POSTOFFICES = 'SET_UKRPOST_POSTOFFICES';
const SET_UKRPOST_REGIONS = 'SET_UKRPOST_REGIONS';

export {
  GET_NOVAPOSHTA_CITIES,
  GET_NOVAPOSHTA_WAREHOUSES,
  GET_NOVAPOSHTA_PRICES,
  SET_NOVAPOSHTA_CITIES,
  SET_NOVAPOSHTA_WAREHOUSES,
  SET_NOVAPOSHTA_PRICES,
  SET_DELIVERY_LOADING,
  SET_FONDY_DATA,
  GET_UKRPOST_CITIES,
  GET_UKRPOST_DISTRICTS,
  GET_UKRPOST_POSTOFFICES,
  GET_UKRPOST_REGIONS,
  SET_UKRPOST_CITIES,
  SET_UKRPOST_DISTRICTS,
  SET_UKRPOST_POSTOFFICES,
  SET_UKRPOST_REGIONS
};
