export const SET_PRODUCTS_FOR_SEARCH_BAR = 'SET_PRODUCTS_FOR_SEARCH_BAR';
export const GET_PRODUCTS_FOR_SEARCH_BAR = 'GET_PRODUCTS_FOR_SEARCH_BAR';
export const SET_SEARCH_BAR_VISIBILITY = 'SET_SEARCH_BAR_VISIBILITY';
export const SET_SEARCH_BAR_LOADING = 'SET_SEARCH_BAR_LOADING';
