export const SET_RATE = 'SET_RATE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const SET_COMMENTS_LOADING = 'COMMENTS_LOADING';
export const SET_UPDATING_COMMENT = 'UPDATING COMMENT';
export const SET_COMMENTS_LIMIT = 'SET_COMMENTS_LIMIT';
