export const SET_ORDER = "SET_ORDER";
export const SET_LOADING = "SET_LOADING";
export const SET_IS_ORDER_CREATED = "SET_IS_ORDER_CREATED";
export const GET_IS_ORDER_CREATED = "GET_IS_ORDER_CREATED";
