const ADD_TO_CART = 'ADD_TO_CART';
const CLEAR_CART = 'CLEAR_CART';
const SET_CART = 'SET_CART';
const SET_CART_ITEM_QUANTITY = 'SET_CART_ITEM_QUANTITY';

export { ADD_TO_CART, CLEAR_CART, SET_CART, SET_CART_ITEM_QUANTITY };
