export const GET_HOMEPAGE_SLIDER_IMAGES = 'GET_HOMEPAGE_SLIDER_IMAGES';
export const SET_HOMEPAGE_SLIDER_IMAGES = 'SET_HOMEPAGE_SLIDER_IMAGES';
export const SET_HOMEPAGE_SLIDER_IMAGES_LOADING = 'SET_HOMEPAGE_SLIDER_IMAGES_LOADING';
