const GET_CATEGORIES = 'GET_CATEGORIES';
const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_CATEGORIES_LOADING = 'SET_CATEGORIES_LOADING';

export { GET_CATEGORIES, SET_CATEGORIES, SET_CATEGORIES_LOADING };
